vaadin.devmode.liveReload.enabled=true
spring.main.allow-circular-references=true
server.servlet.session.persistent=false
management.endpoints.shutdown.enabled=true
vaadin.devmode.devTools.enabled=false
vaadin.copilot.enabled=false