vaadin.allowed-packages=software/xdev,com/vaadin/flow
vaadin.devmode.liveReload.enabled=true
vaadin.devmode.usageStatistics.enabled=false
spring.main.allow-circular-references=true
server.servlet.session.persistent=false
management.endpoints.shutdown.enabled=true
vaadin.devmode.devTools.enabled=false
vaadin.copilot.enabled=false

# Set these values in your env
spring.security.oauth2.client.registration.google.client-id:${GA_ID}
spring.security.oauth2.client.registration.google.client-secret:${GA_SECRET}
